### ISSUE TITLE
get customer group in sales order

### ISSUE THREAD

**Issue by myselfgaurav** [magento-hackathon/GridControl#8]
i made changes to gridconrol.xml

					<join table="sales/order" condition="main_table.entity_id={{table}}.entity_id" field="customer_id"/>

this give me customer id how can i use it to get customer group

**Comment by Schrank** [comment]
Just change customer_id to `group_id`. Then you have the group_id.

But I think you can't add the customer group name. The problem is, that you need to first join from sales_flat_order_grid to sales_flat_order and then to customer_group. The second join can't be made at the moment. At least I didn't find fast a way. You are welcome to read in `https://github.com/magento-hackathon/GridControl/blob/master/src/app/code/community/FireGento/GridControl/Model/Observer.php` maybe you find a way.

If not feel free to send a PR to join tables without fields :-)
